#!/usr/bin/env bash

# Получаем краткий хеш коммита
GIT_COMMIT=$(git rev-parse --short HEAD || echo "unknown")

# Получаем дату (в ISO 8601 формате)
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Версию можно брать из тега, либо задавать вручную
# Пример: берем последнюю аннотированную версию (тег) или "dev"
GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev")

# Генерируем файл version_gen.go
cat <<EOF > version_gen.go
// Code generated by generate_version.sh; DO NOT EDIT.

package main

func init() {
    buildVersion = "${GIT_TAG}"
    buildCommit  = "${GIT_COMMIT}"
    buildDate    = "${BUILD_DATE}"
}

EOF

echo "version_gen.go is generated successfully."
